/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1bbb276b-21f8-4413-99eb-24ae80a60588",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NtfZOWFn4",
    "aws_user_pools_web_client_id": "lq4thfc77r28jff29rbp5qin9",
    "oauth": {}
};


export default awsmobile;
